{% set version = "1.0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-imbalance
  version: {{ version|replace("-", "_") }}

source:
  fn: imbalance_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/imbalance_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/imbalance/imbalance_{{ version }}.tar.gz
  sha256: 3a44ee386faac9a08d09f9e8df48689aa9d635e1e35aefb40a0b0584fab8c791

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - llvm-openmp                # [osx]
  host:
    - r-base
    - r-c50
    - r-fnn
    - r-kernelknn
    - r-rcpp
    - r-rcpparmadillo
    - r-bnlearn
    - r-ggplot2
    - r-mvtnorm
    - r-smotefamily
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-c50
    - r-fnn
    - r-kernelknn
    - r-rcpp
    - r-rcpparmadillo
    - r-bnlearn
    - r-ggplot2
    - r-mvtnorm
    - r-smotefamily
    - llvm-openmp                # [osx]

test:
  commands:
    - $R -e "library('imbalance')"           # [not win]
    - "\"%R%\" -e \"library('imbalance')\""  # [win]

about:
  home: http://github.com/ncordon/imbalance
  license: GPL (>= 2)
  summary: 'Class imbalance usually damages the performance of classifiers. Thus, it is important to treat data before applying a classifier algorithm. This package
    includes recent resampling algorithms in the literature: (Barua et al. 2014) <doi:10.1109/tkde.2012.232>; (Das et al. 2015) <doi:10.1109/tkde.2014.2324567>, (Zhang
    et al. 2014) <doi:10.1016/j.inffus.2013.12.003>; (Gao et al. 2014) <doi:10.1016/j.neucom.2014.02.006>; (Almogahed et al. 2014) <doi:10.1007/s00500-014-1484-5>.
    It also includes an useful interface to perform oversampling.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
