appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: J97k/MfXdF5BaTH7wgH/NIGwvdqqo1QP4rRge9gJVqPb1fma+HVw32WmbzRKhXnG5p8NGif2wiCzDS1h3ZOGxYs2kTJa7O6mLgZkqIXa0BBLBM9vIeeDu6Ha432KvDOunUQE+pwtHjZRKz9TY5nzvceQCDTt/OS1ww4i0VnkCfeIkyiBJTxrglsN6/eKpEOtTgho7j7OjOT28VoyEFoO5R5ko2fvs9pSqUvzsP5+g78pfl/8MpeyFRkrA76dVAB5e8EtNHSg7Ny215v40dm/XsVp1REuhEruOOGgTwHbA9n0sYgYeBrtzmdX9euG20QlPya2nVsIKNyBtzpY8LXn3TYGWbMJMwX8fH/12IMOgDd2Nmj8m26e8pyAtiOHrJyd/CjgNGaiE1ryENoPW+BPUCULEg/7HnVhgY39njxfJhfRf53Ruh17bF2zcMAGqRBvFFJHZWaJkvLbzyv1LI5e6br+MDHl72G7qGK5LJI0fVT9nNZ9R3BzfVltrWEKObGFYHu2elFWqpN979jcolPtdmn8ke4SzlQXy777LnWhyxl5zYPZBkIBvVRrnmvW/SqlVyCjcIz4iepmNfjtqO9jkCTsM6xiV71h+xGUj+RvKBEKOXWFQ+RPYzBzx6SvfLntk1+dvKYc07ETH+Tgm98puNFAI6LIRrKbkCefARMfY0E=}
bot:
  automerge: true
