travis:
  secure:
    BINSTAR_TOKEN: UQRS79FddruLeRZYMQlpQtw/F7dqW44BZUOs28SL4rpkS5KAMX00u8YvKU4zh4hlYYyIHdXik8BeZba7umDVWRlNrcaRwNYN9RLrH6VKZn2g3MT0DzU1q/bHpZ7AhmIUNwG/93V1Fnc/hpklUfHLl/ydqSOLHCHP7FXMFY4OMc9+VubW3eqFiNz146wPsoAA0mpEP+lFLFTyMeV0pCfBJDSMrYpnq+2wkjnImwVE0pLUEazl3TzBscoO6dI6K6Rz4pk8OOyNjnTOMFjtoHQwd5HZNbrd7zRKwHKChIleCFeEKtJPCGiuntPFvGg62XdpM1b/OnZQzqd11jd6S34r+4/84q87943en082M7c9GPeTXeoJ0JAlr0Ll8BIVwOVEM5OrcpYWlz+LAUVj3ArK6GsWZoSGhMqB/3o1a4TtAnuaUpkaOG7+HuOdQvfcw3t+yriZ9ivI+vJEMKQTfg+EqPFWEtFd4rxdeGIFi1RPRhaKJmp6EhY9zeRduSkrCoW4Zo9Uh2iSvbTulH7LqiwScvUcu0+0o1WW1ApCx/l0PTM/NsfD51+9m3HVm0A9ET+ZeGYfdTtL3nbqJ7q9aGxJ18T3eoy+Y6NrhmlVOz8N1/qZTNUsJ9uFYCGbNfFStZwjRxzB3wdneoUQCMK+9ookeOZRpf9ybqz0DbEpXYSRvCg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
